AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Central Hub VPC with public/private subnets (2 AZs),
  Transit Gateway, TGW VPC attachment, and RAM sharing to Spoke accounts.
  NAT Gateways intentionally removed.

############################################################
# PARAMETERS
############################################################
Parameters:
  EnvironmentName:
    Type: String
    Default: Hub

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.11.0/24

  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.12.0/24

  SpokeACIDR:
    Type: String
    Default: 10.1.0.0/16

  SpokeBCIDR:
    Type: String
    Default: 10.2.0.0/16

  SpokeAAccountId:
    Type: String

  SpokeBAccountId:
    Type: String

  TransitGatewayDescription:
    Type: String
    Default: Central TGW for Hub-Spoke Architecture

############################################################
# RESOURCES
############################################################
Resources:

  ############################
  # VPC
  ############################
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  ############################
  # INTERNET GATEWAY
  ############################
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  ############################
  # SUBNETS
  ############################
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false

  ############################
  # ROUTE TABLES
  ############################
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

  ############################
  # TRANSIT GATEWAY
  ############################
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      Description: !Ref TransitGatewayDescription
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      DnsSupport: enable

  HubVPCAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref VPC
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  ############################
  # HUB → SPOKE ROUTES
  ############################
  RouteToSpokeA1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: !Ref SpokeACIDR
      TransitGatewayId: !Ref TransitGateway

  RouteToSpokeB1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: !Ref SpokeBCIDR
      TransitGatewayId: !Ref TransitGateway

  RouteToSpokeA2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: !Ref SpokeACIDR
      TransitGatewayId: !Ref TransitGateway

  RouteToSpokeB2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: !Ref SpokeBCIDR
      TransitGatewayId: !Ref TransitGateway

  ############################
  # RAM SHARE
  ############################
  TransitGatewayRAMShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: !Sub ${EnvironmentName}-TGW-Share
      AllowExternalPrincipals: true
      Principals:
        - !Ref SpokeAAccountId
        - !Ref SpokeBAccountId
      ResourceArns:
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${TransitGateway}

############################################################
# OUTPUTS
############################################################
Outputs:
  VPCId:
    Value: !Ref VPC

  TransitGatewayId:
    Value: !Ref TransitGateway

  HubVPCAttachmentId:
    Value: !Ref HubVPCAttachment

  TGWRAMShareArn:
    Value: !Ref TransitGatewayRAMShare
